baseURL = "https://sverona.dev"
languageCode = "en-us"
title = "S. Verona Lišková"

theme = "semiotic"

math = false

[markup]
  [markup.tableOfContents]
    ordered = false
  [markup.highlight]
    style = "algol_nu"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog"
        weight = 1
    [[menu.main]]
        name = "github"
        url = "https://github.com/sverona"
        weight = 3
    [[menu.main]]
        name = "about"
        url = "/about"
        weight = 4
