baseURL = "https://www.sverona.dev/"
languageCode = "en-us"
title = "S. Verona Malone"

theme = "semiotic"

math = false

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog"
        weight = 1
    [[menu.main]]
        name = "projects"
        url = "/projects"
        weight = 2
    [[menu.main]]
        name = "github"
        url = "https://github.com/sverona"
        weight = 3
    [[menu.main]]
        name = "about"
        url = "/about"
        weight = 4
